services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - mariadb  # Add dependency on mariadb
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app  # Map local frontend directory to container
    environment:
      - NODE_ENV=development

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ./auth_service:/usr/src/app  # Map local auth_service directory to container
    environment:
      - PYTHONUNBUFFERED=1

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MariaDB
      MYSQL_DATABASE: app_db  # Specify the database name
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mariadb-data:/var/lib/mysql  # Persist database data

  backend:
    build: ./backend
    ports:
      - "8002:8002"
    depends_on:
      - auth-service
      - mariadb
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
