services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - auth-service
      - mariadb
      - mongodb  # Add dependency on MongoDB
    networks:
      - app-network
    volumes:
      - ./frontend:/usr/src/app  # Map local frontend directory to container
    environment:
      - NODE_ENV=development

  auth-service:
    build: ./auth_service
    ports:
      - "8001:8001"
    networks:
      - app-network
    volumes:
      - ./auth_service:/usr/src/app  # Map local auth_service directory to container
    environment:
      - PYTHONUNBUFFERED=1

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Set the root password for MariaDB
      MYSQL_DATABASE: app_db  # Specify the database name
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - mariadb-data:/var/lib/mysql  # Persist database data

  mongodb:  # New MongoDB service
    image: mongo:latest  # Using the official MongoDB image
    container_name: mongodb
    command:
      - --auth
    ports:
      - "27017:27017"  # Expose the default MongoDB port
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Set the root username
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword  # Set the root password
      - MONGO_INITDB_DATABASE=app_db  # Specify the database name
    networks:
      - app-network
    volumes:
      - mongodb-data:/data/db  # Persist MongoDB data

  backend:
    build: ./backend
    ports:
      - "8002:8002"
    depends_on:
      - auth-service
      - mariadb
      - mongodb  # Add dependency on MongoDB
    networks:
      - app-network
    volumes:
      - ./backend:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1


  analytics-service: # New analytics service
    build: ./analytics_service
    ports:
      - "8003:8003"
    depends_on:
      - mariadb
      - mongodb  # Ensure MongoDB is available
    networks:
      - app-network
    volumes:
      - ./analytics_service:/usr/src/app
    environment:
      - PYTHONUNBUFFERED=1
      - MYSQL_HOST=mariadb
      - MYSQL_DB=app_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpassword
      - MONGO_URI=mongodb://root:rootpassword@mongodb:27017/app_db  # MongoDB URI
    command: [ "python", "analytics_service.py" ]  # Command to run the service

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
  mongodb-data:  # Volume for MongoDB data
